<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="manipulator">

    <!-- VARIABLE DEFINITIONS -->
    <xacro:property name="link_0_length" value="0.5"/>
    <xacro:property name="link_1_length" value="0.5"/>
    <xacro:property name="link_2_length" value="0.5"/>
    <xacro:property name="link_3_length" value="${link_0_length + 2*link_width}"/>
    <xacro:property name="link_width" value="0.1"/>
    <xacro:property name="half_link_width" value="${link_width/2}"/>


    <!-- BASE LINK -->
    <link name="base_0"></link>

    <joint name="base_joint_0" type="fixed">
        <parent link="base_0"/>
        <child link="base_1"/>
    </joint>

    <link name="base_1">
        <visual name="base_1">
            <origin xyz="0.0 0.0 ${link_0_length/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${link_width} ${link_width} ${link_0_length}"/>
            </geometry>
            <material name="white">
                <color rgba="1.0 1.0 1.0 1.0"/>
                <texture filename=""/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${link_0_length/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${link_width} ${link_width} ${link_0_length}"/>
            </geometry>
        </collision>
    </link>


    <joint name="joint_0" type="revolute">
        <origin xyz="0.0 0.0 ${link_0_length}" rpy="0.0 0.0 0.0"/>
        <parent link="base_1"/>
        <child link="link_1"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    </joint>

    <!-- LINK 1 -->
    <link name="link_1">
        <inertial>
            <origin xyz="${(link_1_length/2) - half_link_width} 0.0 ${half_link_width}" rpy="0.0 0.0 0.0"/>
            <mass value="1.0"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual name="link_1">
            <origin xyz="${(link_1_length/2) - half_link_width} 0.0 ${half_link_width}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${link_1_length} ${link_width} ${link_width}"/>
            </geometry>
            <material name="red">
                <color rgba="1.0 0.0 0.0 1.0"/>
                <texture filename=""/>
            </material>
        </visual>
        <collision>
            <origin xyz="${(link_1_length/2) - half_link_width} 0.0 ${half_link_width}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${link_1_length} ${link_width} ${link_width}"/>
            </geometry>
        </collision>
    </link>


    <joint name="joint_1" type="revolute">
        <origin xyz="${link_1_length - 2*half_link_width} 0.0 ${half_link_width}" rpy="0.0 0.0 0.0"/>
        <parent link="link_1"/>
        <child link="link_2"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    </joint>

    <!-- LINK 2 -->
    <link name="link_2">
        <inertial>
            <origin xyz="${(link_2_length/2) - half_link_width} 0.0 ${link_width}" rpy="0.0 0.0 0.0"/>
            <mass value="1.0"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual name="link_2">
            <origin xyz="${(link_2_length/2) - half_link_width} 0.0 ${link_width}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${link_2_length} ${link_width} ${link_width}"/>
            </geometry>
            <material name="green">
                <color rgba="0.0 1.0 0.0 1.0"/>
                <texture filename=""/>
            </material>
        </visual>
        <collision>
            <origin xyz="${(link_2_length/2) - half_link_width} 0.0 ${link_width}" rpy="0.0 0.0 0.0"/>
            <geometry>s
                <box size="${link_2_length} ${link_width} ${link_width}"/>
            </geometry>
        </collision>
    </link>

    <joint name="joint_2" type="revolute">
        <origin xyz="${link_2_length - 2*half_link_width} ${-half_link_width} ${link_width}" rpy="${pi/2} 0.0 0.0"/>
        <parent link="link_2"/>
        <child link="link_3"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    </joint>

    <!-- LINK 3 -->
    <link name="link_3">
        <inertial>
            <origin xyz=" 0.0 ${-(link_3_length/2) + half_link_width} ${half_link_width}" rpy="0.0 0.0 ${pi/2}"/>
            <mass value="1.0"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
        <visual name="link_3">
            <origin xyz=" 0.0 ${-(link_3_length/2) + half_link_width} ${half_link_width}" rpy="0.0 0.0 ${pi/2}"/>
            <geometry>
                <box size="${link_3_length} ${link_width} ${link_width}"/>
            </geometry>
            <material name="blue">
                <color rgba="0.0 0.0 1.0 1.0"/>
                <texture filename=""/>
            </material>
        </visual>
        <collision>
            <origin xyz=" 0.0 ${-(link_3_length/2) + half_link_width} ${half_link_width}" rpy="0.0 0.0 ${pi/2}"/>
            <geometry>
                <box size="${link_3_length} ${link_width} ${link_width}"/>
            </geometry>
        </collision>
    </link>

    <!-- END EFFECTOR -->
    <!-- <link name="end_effector">
        <inertial>
            <origin xyz="1.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        <visual name="end_effector">
            <origin xyz="1.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.2 0.2 0.2"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.0 0.0 0.0"/>
            </geometry>
        </collision>
    </link> -->
</robot>